### ISSUE TITLE
[Bug]腾讯tmpsecret

### ISSUE THREAD

**Issue by NezHacker** [teamssix/cf#108]
![image](https://user-images.githubusercontent.com/87883732/182291784-844824c4-960a-425a-8d9f-3f1d2c068d15.png)
好像并不支持 腾讯的tmpsecret(都是新生成的secret)

**Comment by teamssix** [comment]
感谢反馈，最近我排查下这个bug

**Comment by Amzza0x00** [comment]
@NezHacker 哈喽，反馈的问题已解决

**Comment by NezHacker** [comment]
![image](https://user-images.githubusercontent.com/87883732/182517301-021c07d4-23da-4a0e-bdf5-ced9e6296fbc.png)
![LG@8GRT@_M$ K7Q0VIYWEDY](https://user-images.githubusercontent.com/87883732/182517331-a4a4dfe5-9f98-400a-9fc6-05a06e5daddd.png)
师傅你好我用的最新版linux amd64 依然不太行会爆签名错误。。但secret是新生成的。有可能是我渗透环境(对方的问题吗，做了一些限制或是怎样)

**Comment by Amzza0x00** [comment]
修复的代码在beta分支下，还没同步到main分支下呢，稍等

**Comment by NezHacker** [comment]
是我太快了吗哈哈 到时候会自动更新吗 还是要重新下

**Comment by Amzza0x00** [comment]
@NezHacker 你的key泄漏了，删了吧

**Comment by NezHacker** [comment]
我这个 是上传点的tmpsecret(不是固定的 每次上传都会变)的

**Comment by NezHacker** [comment]
临时的的 但是没标tmpsecret
