### ISSUE TITLE
[Bug] ./cf tencent console 报错

### ISSUE THREAD

**Issue by NezHacker** [teamssix/cf#117]
![image](https://user-images.githubusercontent.com/87883732/183237815-2c669485-5c1f-4173-a317-05fb40a706ca.png)
./cf tencent console 报错
panic: runtime error: invalid memory address or nil pointer dereference
![image](https://user-images.githubusercontent.com/87883732/183237835-d1987d69-5cfd-463e-a391-8ea3024803d5.png)
AK SK 是meicu没错的可以登陆 感觉是由于权限过低导致的吗

**Comment by teamssix** [comment]
感谢反馈，这两天我排查一下哈

**Comment by teamssix** [comment]
@NezHacker 我试了一下，可以正常接管的，会不会是你的 AK 权限不足的原因？后门我给 CF 加上接管控制台前先判断权限的功能

**Comment by Amzza0x00** [comment]
@teamssix 把HandleErrNoExit处理换成HandleErr就好了，失败原因也会打印到控制台。

**Comment by Dawnnnnnn** [comment]
这个就是AK权限不足，先`HandleErr`吧

`接管控制台前先判断权限`需要 

列子用户列表 -> 遍历查询每个子用户对应的AKSK-> 与当前使用AKSK做对比 -> 查询对应子用户绑定的策略 -> 判断该策略是否满足接管控制台的最小权限

最麻烦的就是最后一步，需要先找到这些策略

还有一个问题，如果第一步 `列子用户列表` 就无权限应该怎么处理

感觉报错不如直接给用户直接返回方便(懒)

**Comment by NezHacker** [comment]
是这样的 报错原因 是 AK 没有操作cvm的权限 只对应了一个桶
