### ISSUE TITLE
baidu bos[Feat]

### ISSUE THREAD

**Issue by cyal1** [teamssix/cf#132]
https://cloud.baidu.com/doc/BOS/s/Ojwvyrpgd#%E4%BD%BF%E7%94%A8sts%E5%88%9B%E5%BB%BAbosclient

**Comment by teamssix** [comment]
@cyal1 额，你这能描述的详细些嘛？你是想表达希望增加百度云 BOS 的功能模块吗？

**Comment by teamssix** [comment]
考虑到使用的用户体量以及开发成本，目前暂时没有覆盖百度云的计划，即使有这个估计也要到明年了，关于 CF 的新功能排期可以看这里 https://github.com/teamssix/cf/discussions/130
