### ISSUE TITLE
[Perf] <Readme 内容过期>

### ISSUE THREAD

**Issue by Esonhugh** [teamssix/cf#148]
### 描述你希望优化的功能 (Describe your needs)

README 文档的图片的指令是过时的 版本变更修改命令可能会导致用户不习惯

此外建议使用 Mermaid 进行渲染 使得内容可以被后期开发者维护

**Comment by teamssix** [comment]
后面我会基于 v0.4.x 版本发布一些 CF 实践的文章，这样也有利于师傅们熟悉 CF 的命令。

**Comment by Esonhugh** [comment]
可以 越来越成熟了。之前写的时候在你的框架上加模块 现在你给移到框架里实现了 挺好的。

不过 readme 那张图不考虑用 mermaid 生成嘛? 这样你就不用一次又一次的修那个图了  直接交给开发者 git 管理就行了 也不用 jsdelivery 图床

**Comment by teamssix** [comment]
用 mermaid 生成确实是比较方便，但是感觉没有很美观，所以就不考虑啦，而且现在的这个思维导图等回头发推或者发文章的时候也会用到。

**Comment by Esonhugh** [comment]
> 用 mermaid 生成确实是比较方便，但是感觉没有很美观，所以就不考虑啦，而且现在的这个思维导图等回头发推或者发文章的时候也会用到。

Ok（ 问题不大
