### ISSUE TITLE
[Bug] aliyun console功能的错误判断失效

### ISSUE THREAD

**Issue by funnyndk** [teamssix/cf#163]
### 描述你遇到的问题 (What happened?)

aliyun console功能的错误判断失效，未成功接管的情况下cf仍然显示接管成功。
存在主域名情况下，使用默认接管后，得到如下结果：
![issue](https://user-images.githubusercontent.com/56995030/191206924-a83aa5eb-b5de-4b82-9717-27563e6035d9.PNG)
用户名会变为crossfire@主域名，账户正常创建。

但是后续AK失效后，使用aliyun console功能，得到如下结果：
![issue2](https://user-images.githubusercontent.com/56995030/191207552-ecc04c5c-5343-47bd-b7db-6783258b1129.PNG)
用户名会变为12345ee@，登录阿里云后台查看用户未创建成功。

### 复现步骤 (Steps To Reproduce)

1.AK被禁用
2.使用cf aliyun console功能
3.cf显示接管成功但实际上运行失败

### 操作系统 (Operating System)

Linux

### 系统类型 (System Type)

amd64

### CF 版本 ( CF Version)

0.4.0

**Comment by teamssix** [comment]
感谢师傅反馈，下个版本我把这个地方优化一下哈
