### ISSUE TITLE
[Bug] Program will not stop when Ctrl-c is pressed.

### ISSUE THREAD

**Issue by Esonhugh** [teamssix/cf#173]
### 描述你遇到的问题 (What happened?)

当尝试 config key 的时候 发现自己输入错误第一时间执行 ctrl -c 的时候 会发现程序无法正常退出 

### 复现步骤 (Steps To Reproduce)

cf config 
<press C-c>

### 操作系统 (Operating System)

MacOS

### 系统类型 (System Type)

arm64

### CF 版本 ( CF Version)

0.4.0

### 补充信息 (Anything else?)

 errutils 包中没有对用户取消 interrupt 做出正确的响应

**Comment by Esonhugh** [comment]
#174

**Comment by Esonhugh** [comment]
先加这个吧 错误处理那块是不是可以改成注册的形式 让每个包在 启动的时候注册对应的错误信息 方便维护？

**Comment by teamssix** [comment]
感谢反馈🙏

**Comment by Esonhugh** [comment]
> 感谢反馈🙏

所以我的 PR 有什么问题吗？

**Comment by teamssix** [comment]
> noexit的 errorhandle 函数还是有这个问题.... 而不是改一行就完事了

我试了下，改这一行后，在配置的时候，按 Ctrl + C 程序已经能够停止了

**Comment by teamssix** [comment]
> 所以我的 PR 有什么问题吗？

因为我本地还有代码没 Pull 上去，如果同步你的 PR 的话，go mod 、sum 文件会有冲突

**Comment by Esonhugh** [comment]
> > 所以我的 PR 有什么问题吗？
> 
> 因为我本地还有代码没 Pull 上去，如果同步你的 PR 的话，回头文件会有冲突

好吧 所以已经开始写华为云了？

**Comment by teamssix** [comment]
> 好吧 所以已经开始写华为云了？

目前是在写 AWS 的
