### ISSUE TITLE
emm 修了aws 但是其他的ls 都出现了问题.

### ISSUE THREAD

**Issue by bambooqj** [teamssix/cf#202]
### 描述你遇到的问题 (What happened?)

加入 --flushCache 参数后,本地缓存仍不刷新.扫描有,本地没有...

### 复现步骤 (Steps To Reproduce)

1. 加入 --flushCache 枚举 cvm服务器
2. 去掉 刷新参数.仍旧没有主机

### 操作系统 (Operating System)

Windows

### 系统类型 (System Type)

amd64

### CF 版本 ( CF Version)

最新的 (Latest)

**Comment by teamssix** [comment]
会不会是本身就没有 cvm 主机

**Comment by bambooqj** [comment]
--flushCache 中有数据库没加上

**Comment by teamssix** [comment]
感谢反馈，bug 确实存在，现在已修复，如果师傅你急用可以自行 clone 仓库，然后 go build 打包，如果不急也可以等下个版本发布。

不过我记得之前这个功能是正常的，估计是因为后面加了一些新功能引发了这个 bug
