### ISSUE TITLE
MissingParameter

### ISSUE THREAD

**Issue by LinLuosheng** [teamssix/cf#211]
### 描述你遇到的问题 (What happened?)

执行命令报错MissingParameter

### 复现步骤 (Steps To Reproduce)

1

### 操作系统 (Operating System)

MacOS

### 系统类型 (System Type)

amd64

### CF 版本 ( CF Version)

最新的 (Latest)

### 补充信息 (Anything else?)

ErrorCode: MissingParameter
Recommend: https://next.api.aliyun.com/troubleshoot?q=MissingParameter&product=Ecs
RequestId: 7C8F316E-F081-3D70-8D18-D46CD103E1AB
Message: The input parameter "CommandId" that is mandatory for processing this request is not supplied.
RespHeaders: map[Access-Control-Allow-Origin:[*] Connection:[keep-alive] Content-Length:[313] Content-Type:[application/json;charset=utf-8] Date:[Fri, 24 Feb 2023 10:10:36 GMT] X-Acs-Request-Id:[7C8F316E-F081-3D70-8D18-D46CD103E1AB] X-Acs-Trace-Id:[33af20fdb18a710ffb57fd7ff88223c4]]

**Comment by teamssix** [comment]
额，所以你是执行的啥命令？

**Comment by LinLuosheng** [comment]
没事了，好像是服务器有点问题
