### ISSUE TITLE
[Bug] <v0.4.4 huawei执行出错>

### ISSUE THREAD

**Issue by wpf97** [teamssix/cf#213]
### 描述你遇到的问题 (What happened?)

./cf huawei obs ls
[2023-03-03 21:01:36]  INFO 在全部区域下获取到 8 条 obs Bucket 信息 (Find 8 obs Bucket under all areas)
[2023-03-03 21:01:45] ERROR obs: service returned error: Status=500 Server Error, Code=InternalError, Message=We encountered an internal error. Please try again., RequestId=00000186A7906B7980584FCF09B4A888
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x201c459]

goroutine 1 [running]:
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.GetBucketRegion({0xc0003883d0, 0xa})
	/home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obsls.go:31 +0x79
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.PrintBucketsListRealTime({0x250d673, 0x3}, {0x250d673, 0x3})
	/home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obsls.go:123 +0x325
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.PrintBucketsList({0x250d673, 0x3}, 0x6f?, {0x250d673, 0x3})
	/home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obsls.go:158 +0x8a
github.com/teamssix/cf/cmd/huawei.glob..func1(0x3c53000?, {0x250e9e9?, 0x0?, 0x0?})
	/home/runner/work/cf/cf/cmd/huawei/obs.go:37 +0xbe
github.com/spf13/cobra.(*Command).execute(0x3c53000, {0x3c8e4e0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x3c4e280)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/teamssix/cf/cmd.Execute()
	/home/runner/work/cf/cf/cmd/root.go:50 +0x55
main.main()
	/home/runner/work/cf/cf/main.go:12 +0x17

### 复现步骤 (Steps To Reproduce)

./cf huawei obs ls

### 操作系统 (Operating System)

MacOS

### 系统类型 (System Type)

amd64

### CF 版本 ( CF Version)

最新的 (Latest)

**Comment by teamssix** [comment]
看样子是网络的问题，你可以看看是不是本地网络有啥问题

**Comment by teamssix** [comment]
由于长时间未回复，将关闭此 Issue
