### ISSUE TITLE
[Feat] 是否支持创建阿里云或腾讯云按量付费云服务器？

### ISSUE THREAD

**Issue by mexhfl** [teamssix/cf#215]
### 描述你希望增加的功能 (Describe the features you wish to add)

详细描述你希望增加的功能，并且描述为什么想要增加这个功能以及意义，描述的越完善该反馈越有可能被采纳。(Describe in detail the feature you want to add, and describe why you want to add this feature and the significance, the better the description the more likely the feedback will be adopted.)

**Comment by teamssix** [comment]
支持这个的意义在哪里？似乎和 CF 的用途不太一样哎

**Comment by teamssix** [comment]
可以了解一下 Terraform，这个工具是专门做这种工作的
