### ISSUE TITLE
公网 IP (PUBLIC IP) 为[]是什么意思，执行命令一直无响应

### ISSUE THREAD

**Issue by rootGH** [teamssix/cf#216]
### 描述你遇到的问题 (What happened?)

刚好这个ECS执行命令就一直无响应，怎么回事呢

### 复现步骤 (Steps To Reproduce)

可以获取到ECS资源等。

### 操作系统 (Operating System)

Windows

### 系统类型 (System Type)

amd64

### CF 版本 ( CF Version)

最新的 (Latest)

**Comment by teamssix** [comment]
可以加上 --logLevel trace 看看有没有什么报错信息

**Comment by teamssix** [comment]
公网 IP 为说明没有公网 IP，一直没有响应可能是主机云助手未处于运行状态，在下个版本中，执行命令前会检查云助手是否安装
