### ISSUE TITLE
批量执行任务的时候如果主机有没有装云助手的话会提示超时

### ISSUE THREAD

**Issue by Lao-66** [teamssix/cf#232]
批量执行任务的时候如果主机有没有装云助手的话会提示超时，导致后续的流程不会继续进行。
大佬方便的话修复一下。

**Comment by Lao-66** [comment]
@teamssix 师傅，这里的逻辑能不能修改一下。批量执行任务的时候不论单个任务执行是否成功都保证让程序把后续的执行完毕。 我刚测试，遇到命令执行失败的情况，循环也就断掉了。

**Comment by teamssix** [comment]
这个确实需要加上，目前是做了检测主机存活和是否安装云助手，下个版本我把命令执行失败后继续执行的功能给加上

**Comment by Lao-66** [comment]
@teamssix  写了大佬，坐等下版本啦。
