### ISSUE TITLE
[Bug] 腾讯云找不到云主机

### ISSUE THREAD

**Issue by VVeakee** [teamssix/cf#237]
### 描述你遇到的问题 (What happened?)

使用行云管家可以搜索到有云主机
地区位于,华北地区(上海)
![image](https://github.com/teamssix/cf/assets/85714114/91494779-8cc6-4864-8ed8-ff93f5c94669)

但是用cf却找不到
![image](https://github.com/teamssix/cf/assets/85714114/ac91401c-a8fa-4be4-8cdb-57ee165c2b83)
![image](https://github.com/teamssix/cf/assets/85714114/9e0c8aed-be45-418f-b285-212c27c275a2)

### 复现步骤 (Steps To Reproduce)

因密钥涉及企业不方便公开

### 操作系统 (Operating System)

Windows

### 系统类型 (System Type)

amd64

### CF 版本 ( CF Version)

最新的 (Latest)

**Comment by teamssix** [comment]
不应该啊，可以使用 --logLevel trace 看看有没有什么报错信息

**Comment by teamssix** [comment]
可以加上 --logLevel trace --flushCache 命令看看，会不会是因为本地有缓存什么的

**Comment by VVeakee** [comment]
--flushCache已解决
