### ISSUE TITLE
希望增加对OSS跨域规则操作功能的添加

### ISSUE THREAD

**Issue by Gofreedom0** [teamssix/cf#35]
默认不开启CORS，开启需要进行接口操作

见
https://help.aliyun.com/document_detail/32001.htm?spm=a2c4g.11186623.0.0.372421dc2M1gHs#reference-wtg-ttc-xdb

**Comment by teamssix** [comment]
是指为 OSS 增加 CORS 规则吗？增加这个规则对于红队而言有什么价值吗？

**Comment by teamssix** [comment]
由于长时间未回复，已关闭此 Issue
