### ISSUE TITLE
[Perf] 多 AKSK 切换与管理模块

### ISSUE THREAD

**Issue by Esonhugh** [teamssix/cf#62]
**你的需求是否与你所遇到的问题有关？**
当 红队成员遇到多个 AKSK 的时候，需要切换或者管理 AKSK 我感觉这个功能还能做的更好。

**描述你希望的解决方案**
增加一个 key 的管理模块

通过在 .cf/config 配置文件中存取数据进行 AKSK 的管理

**Comment by teamssix** [comment]
这个需求功能确实有必要加上，后面我想想怎么加比较合适，感谢师傅。

**Comment by Esonhugh** [comment]
> 这个需求功能确实有必要加上，后面我想想怎么加比较合适，感谢师傅。

我有在写 之前想要更新一下项目结构就是因为这个. github.com/Esonhugh/cf 用的配置文件方法存储. 师傅可以给点指导嘛?

**Comment by teamssix** [comment]
我记得 [pacu](https://github.com/RhinoSecurityLabs/pacu) 是支持多 key 的，师傅或许可以参考参考

**Comment by Esonhugh** [comment]
他看起来是数据库来存的 也就是本地的 Sqlite db file.

```
A local sqlite database maintains data and Pacu provides utilities to easily allow users and modules to store and reference access information and enumerated data found when engaging an AWS environment.
```

我感觉可以引入一个 Sqlite service

**Comment by Esonhugh** [comment]
我细看了 configure 的逻辑 这里有一部分存到了 cache 里. 这部分打算如何处理

**Comment by teamssix** [comment]
cache 文件夹里会放上时间戳和抓取到的云服务资源信息，时间戳主要用来判断每隔24小时就执行一下更新检测，从而判断有没有新版本，时间戳也被用来判断每隔24小时就重新抓取一下云服务资源

**Comment by Esonhugh** [comment]
懂了 可能是因为我本地没有添加 Key 的原因.

**Comment by Esonhugh** [comment]
感觉差不多了

**Comment by teamssix** [comment]
OK，我这两天抽时间看看哈，最近 HW 有些忙

**Comment by teamssix** [comment]
感谢师傅，感谢师傅，辛苦辛苦

**Comment by teamssix** [comment]
感谢师傅提的 PR 哈，不过我发现目前在执行命令，比如 cf alibaba oss ls 的时候，还是读取的配置文件里的 ak，而不是读取数据库里的ak

**Comment by Esonhugh** [comment]
> 感谢师傅提的 PR 哈，不过我发现目前在执行命令，比如 cf alibaba oss ls 的时候，还是读取的配置文件里的 ak，而不是读取数据库里的ak

我只是切换了 配置文件的ak（ 但是我先打好了数据的模板 到时候可以换

**Comment by Esonhugh** [comment]
#73  bug fix

**Comment by Esonhugh** [comment]
看起来得加点文档了（

**Comment by Esonhugh** [comment]
> 感谢师傅提的 PR 哈，不过我发现目前在执行命令，比如 cf alibaba oss ls 的时候，还是读取的配置文件里的 ak，而不是读取数据库里的ak

如果需要在运行命令的时候临时切换 我可以写一个公共函数出来 给 alibaba 和 腾讯的包调

**Comment by Esonhugh** [comment]
@teamssix  wiki 那边怎么编辑？

**Comment by teamssix** [comment]
方法我放到这里了 https://github.com/teamssix/cf/blob/main/CONTRIBUTING.md

**Comment by teamssix** [comment]
已增加到 [v0.3.2](https://github.com/teamssix/cf/releases/tag/v0.3.2) 版本中，再次感谢师傅提交的 pr

**Comment by teamssix** [comment]
在使用了 gorm.io/driver/sqlite 库后，goreleaser 一直编译不通过，奇怪了

**Comment by Amzza0x00** [comment]
@teamssix goreleaser里开启了cgo，go-sqlite库不支持cgo，如果想要交叉编译需安装对应平台编译器。可以更换https://pkg.go.dev/modernc.org/sqlite，同样支持标准database/sql。

**Comment by Amzza0x00** [comment]
@teamssix 也可以静态编译，就是体积大好几倍。我提交的makefile就可以。

**Comment by teamssix** [comment]
> @teamssix 也可以静态编译，就是体积大好几倍。我提交的makefile就可以。

多谢多谢，我试试哈

**Comment by Esonhugh** [comment]
坏了 换一个 Sqlite driver 吧

**Comment by Esonhugh** [comment]
"github.com/glebarez/sqlite" 官方给的是这个
db 里的 Sqlite 换成这个就可以了 是 纯 Go 的 Sqlite 库
那个要改东西 https://pkg.go.dev/modernc.org/sqlite 才能用 gorm 
对应的 grom driver 又 Archive 了

**Comment by teamssix** [comment]
@Esonhugh 还是不行

**Comment by Esonhugh** [comment]
是 go-sqlite 包导致的失败 go-sqlite3 也是 CGO Enable 没法整

**Comment by teamssix** [comment]
> 是 go-sqlite 包导致的失败 go-sqlite3 也是 CGO Enable 没法整

要不换成kv库吧

**Comment by Esonhugh** [comment]
> > 是 go-sqlite 包导致的失败 go-sqlite3 也是 CGO Enable 没法整
> 
> 要不换成kv库吧

配置文件方法存？ 
而且如果其他人要用的话 直接调用就行 也不用写逻辑 
就是分发麻烦的很

**Comment by Esonhugh** [comment]
属于是放弃方便的代码还是放弃方便的分发了

**Comment by Esonhugh** [comment]
应该能跨了

**Comment by Esonhugh** [comment]
CGO_ENABLE=0 GOOS=windows GOARCH=arm  go build -o cf.exe main.go
die 底层库完全不支持该版本编译 其他版本编译通过

**Comment by Esonhugh** [comment]
https://github.com/Esonhugh/cf/releases/tag/v0.0.8 在吗有没有考虑过 不发 arm 版？arm + windows

**Comment by teamssix** [comment]
奇怪哎

**Comment by Esonhugh** [comment]
确实很奇怪 我看过了 都是这个报错 然后其他平台我都自己编译过拉去对应平台跑过 
就是 win arm 编不出来跑不起来 
darwin arm go 本身就没有 support 
linux arm 可以编译 但是我不确定能不能运行

**Comment by teamssix** [comment]
试了下 amd 的都是可以正常运行的，arm 的我这边没环境去测试，不过现在这样也可以，使用 arm32 的人应该极少，感谢师傅哈，辛苦了辛苦了，这个 issue 就先关闭了。

**Comment by Esonhugh** [comment]
一个小问题 这里用了不在维护的 sqlite 支持 cloudquery/sqlite
我昨天又去看了看 cf 的 github action 我发现这个发版报错仅和 arm 有关 
哪怕是需要 CGO 的 driver/sqlite 其实也可以跨编出去而不会报此类错 不支持（但是不能运行 尝试运行会报错 CGO 问题）
在今天我重新尝试跨平台编译的时候 我尝试了依赖 github.com/glebarez/sqlite
我发现是可以正常编译跨平台 并且拖到虚拟机中可以运行的
而该版本处于维护的状态
所以考虑是否需要替换回这个依赖（其他地方不需要改动 只要 db.go 换一行就行）
@teamssix  由于已经发版 这也只是一个小问题 (目前没有发现严重问题) 所以不重新再开 Issue 了.
