### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ghoulsec** [teamssix/cf#95]
The following bugs will appear under the root permission user, even if I clean up ~ / .Cf/cache cache cache files, or update to the latest version, but I can execute the tool when I switch to a user with normal permissions. As shown in the figure.
![bug](https://user-images.githubusercontent.com/99860771/181402177-ab4b62a6-2cec-41fe-a10b-00a72da5b10d.jpg)
![bug2](https://user-images.githubusercontent.com/99860771/181402189-4ab6f273-197c-4329-9674-729265941c87.jpg)

**Comment by teamssix** [comment]
我这边在 kali 下不管是普通用户还是管理员用户，都能正常执行

**Comment by teamssix** [comment]
你把你的环境描述清楚一点吧，按照 issue 的模板来，我这边复现不出来你的这个 bug

**Comment by ghoulsec** [comment]
<img width="667" alt="image" src="https://user-images.githubusercontent.com/99860771/182141106-e3b02b1f-b3e3-4c72-a02c-d198e24ac34d.png">
我root执行不了cf 但是我kali用户可以 我的工具放在了 /home/kali/tools 这个目录 但是是当时以root身份下载的 是最新版本 也清空了缓存文件 但是root账户还是无法执行 在第一次下载这个工具的时候我root账户还是可以执行的 但是第二次开启工具的时候，就开始如图片所示的报错

**Comment by teamssix** [comment]
缓存清的是root用户的缓存还是kali用户的缓存

**Comment by ghoulsec** [comment]
清理的是root用户的缓存



发自我的iPhone


------------------ Original ------------------
From: TeamsSix ***@***.***&gt;
Date: Mon,Aug 1,2022 9:05 PM
To: teamssix/cf ***@***.***&gt;
Cc: ghoulsec ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [teamssix/cf] [Bug]  (Issue #95)

**Comment by teamssix** [comment]
把 ~/.cf 目录删掉试试

**Comment by ghoulsec** [comment]
这样子就好了 是因为根下缓存文件问题么



发自我的iPhone


------------------ Original ------------------
From: TeamsSix ***@***.***&gt;
Date: Tue,Aug 2,2022 6:25 PM
To: teamssix/cf ***@***.***&gt;
Cc: ghoulsec ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [teamssix/cf] [Bug]  (Issue #95)





 
把 ~/.cf 目录删掉试试

**Comment by teamssix** [comment]
具体的我也不清楚，后面打算把缓存数据都放到数据库里，就不会出现类似的问题了

**Comment by ghoulsec** [comment]
好的



发自我的iPhone


------------------ Original ------------------
From: TeamsSix ***@***.***&gt;
Date: Tue,Aug 2,2022 6:53 PM
To: teamssix/cf ***@***.***&gt;
Cc: ghoulsec ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [teamssix/cf] [Bug]  (Issue #95)





 
具体的我也不清楚，后面打算把缓存数据都放到数据库里，就不会出现类似的问题了
